### ISSUE TITLE
Cannot run cf push

### ISSUE THREAD

**Issue by FlorianTolk** [johnlonganecker/rabbitmq-performance-app#2]
I installed cf CLI and tried running cf push. This called me to run either cf login or cf api, which I assumed was to be pointed at localhost:8080.

Running `cf api  http://127.0.0.1:8080` always results in a fail

`Get http://127.0.0.1/v2/info: dial tcp 127.0.0.1:80: connect: connection refused
TIP: If you are behind a firewall and require an HTTP proxy, verify the https_proxy environment variable is correctly set. Else, check your network connection.`

What am I doing wrong?

**Comment by johnlonganecker** [comment]
Are you trying to run this inside Cloud Foundry?

**Comment by FlorianTolk** [comment]
No, it's just on a laptop running Ubuntu 17.10

**Comment by johnlonganecker** [comment]
cf push is a cloud foundry command so if you are not running it in cloud foundry then this command will not work. I am going to close this issue.
